import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import BookingForm from '../../components/BookingForm';
import {useAuth} from '../../context/AuthContext';
import ManagerBookings from '../manager/ManagerBookings';
import {api,confirmAction,notice} from '../../lib/api';
import {DataTable,SearchBar,QuickDeck,Modal,Badge} from '../../components/DataUI';

export default function Page(){const {account}=useAuth();return account?.role==='ROLE_MANAGER'?<ManagerBookings/>:<Bookings/>;}
function Bookings(){const [data,setData]=useState({bookings:[],vehicles:[]}),[services,setServices]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState('');const load=async()=>{try{const [feed,catalog]=await Promise.all([api('/api/workshop/bookings'),api('/api/services')]);setData(feed);setServices(catalog.services);setError('');}catch(e){setError(e.message);}};useEffect(()=>{load();},[]);const cancel=async row=>{if(!(await confirmAction('Cancel this unpaid Pending booking? Its invoice will be voided.')))return;try{await api('/api/workshop/bookings/status/'+row.referenceNumber,{method:'POST',body:JSON.stringify({status:'Cancelled'})});await load();notice('Booking cancelled');}catch(e){setError(e.message);}};const controls=<SearchBar onSearch={setQuery} status={status} setStatus={setStatus} statuses={[...new Set(data.bookings.map(b=>b.status))]} actions={<button className="btn-accent rounded-full px-5 py-3 text-xs" onClick={()=>setSelected({})}>Book service</button>}/>;return <div><h1 className="text-3xl font-black uppercase mb-6">Bookings</h1>{error&&<p role="alert" className="text-brand-accent mb-4">{error} <button onClick={load}>Retry</button></p>}{controls}<QuickDeck>{controls}</QuickDeck><DataTable rows={data.bookings.filter(b=>(!status||b.status===status)&&JSON.stringify(b).toLowerCase().includes(query.toLowerCase()))} columns={[{key:'referenceNumber',label:'Reference',width:'19%'},{key:'invoiceNumber',label:'Invoice',width:'17%',render:b=><Link className="text-brand-accent" to={'/dashboard/invoices/'+b.invoiceId}>{b.invoiceNumber}</Link>},{key:'licensePlate',label:'Vehicle',width:'12%'},{key:'serviceType',label:'Service',width:'15%'},{label:'Appointment',width:'15%',render:b=>b.serviceDate+' '+b.timeSlot},{label:'State',width:'10%',render:b=><Badge value={b.status}/>},{label:'Actions',width:'7%',render:b=><div className="flex gap-3">{b.editable&&<button aria-label="Edit booking" onClick={()=>setSelected(b)}><i aria-hidden="true" className="fa-solid fa-pen text-brand-accent"/></button>}{b.cancellable&&<button aria-label="Cancel booking" onClick={()=>cancel(b)}><i aria-hidden="true" className="fa-solid fa-xmark text-red-500"/></button>}</div>}]} />{selected&&<Modal title={selected.id?'Edit booking':'Book service'} onClose={()=>setSelected(null)}><BookingForm initial={selected} vehicles={data.vehicles} services={services} onSaved={()=>{setSelected(null);load();}}/></Modal>}</div>;}
