import {Input,Select,RequiredMark,FieldValidationContext} from './Validation';
import {useState,useEffect,useRef} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {usePortalTheme,RecordPagination,typedTableActions} from './PortalTheme';
import PortalEditDrawer from './PortalEditDrawer';
import {getStatusTone,getPaginationRange,exportTableToCsv} from '../lib/tableUtils';
export const money=value=>new Intl.NumberFormat('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0);
function LegacyBadge({value}){const text=String(value||'?');const tone=getStatusTone(text);return <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest whitespace-nowrap status-${tone}`}>{text}</span>;}
export function QuickDeck({children}){const [visible,setVisible]=useState(false);const last=useRef(window.scrollY);useEffect(()=>{const scroll=()=>{const y=window.scrollY;setVisible(y>150&&y<last.current);last.current=y;};window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll);},[]);return visible?<div className="fixed top-24 left-0 right-0 z-[60] flex justify-center px-3"><div className="rounded-full bg-[#0a0a0a]/90 backdrop-blur-xl border border-[#333] shadow-[0_20px_50px_rgba(0,0,0,0.9)] p-3 flex gap-3 items-center max-w-full">{children}</div></div>:null;}
export function SearchBar({onSearch,status,setStatus,statuses=[],actions}){const [draft,setDraft]=useState('');const [applied,setApplied]=useState('');const apply=()=>{setApplied(draft);onSearch(draft);};return <div className="flex flex-wrap items-center gap-3"><form noValidate className="relative flex items-center" onSubmit={e=>{e.preventDefault();apply();}}><Input aria-label="Search records" className="input-dark pl-4 pr-20 py-2.5 text-sm w-72 max-w-full" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Search records..."/><div className="search-bar-buttons absolute right-2.5 top-1/2 -translate-y-1/2 flex items-center gap-1.5 pointer-events-auto">{draft&&<button type="button" aria-label="Clear search text" onClick={()=>{setDraft('');onSearch('');}} className="search-bar-btn text-gray-400 hover:text-white inline-flex items-center justify-center"><i aria-hidden="true" className="fa-solid fa-xmark"/></button>}<button aria-label="Search" type="submit" className="search-bar-btn text-brand-accent inline-flex items-center justify-center"><i aria-hidden="true" className="fa-solid fa-magnifying-glass"/></button></div></form>{statuses.length>0&&<div className="relative"><Select aria-label="Filter status" className="input-dark py-2.5 pl-3 pr-8 text-sm appearance-none" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All states</option>{statuses.map(value=><option key={value}>{value}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down absolute right-3 top-3.5 text-[10px] pointer-events-none"/></div>}{(applied||status)&&<button aria-label="Reset filters" className="text-xs text-gray-400" onClick={()=>{setDraft('');setApplied('');onSearch('');setStatus?.('');}}><i aria-hidden="true" className="fa-solid fa-rotate-left mr-2"/>Reset filters</button>}{actions}</div>;}
function LegacyDataTable({rows,columns,rowKey='id',onRow,empty='NO RECORDS FOUND'}){const [page,setPage]=useState(1),[size,setSize]=useState(15);const totalPages=Math.max(1,Math.ceil(rows.length/size));const signature=rows.map(row=>row[rowKey]).join('|');useEffect(()=>setPage(1),[signature,size]);const current=Math.min(page,totalPages);const pageRange=getPaginationRange(current,totalPages);return <div className="mt-6"><div className="overflow-x-auto rounded-xl border border-[#262626]"><table className="w-full table-fixed min-w-[700px] text-sm"><colgroup><col style={{width:'5%'}}/>{columns.map((column,i)=><col key={i} style={{width:column.width||`${95/columns.length}%`}}/>)}</colgroup><thead className="bg-[#1a1a1a] text-[10px] uppercase tracking-widest text-gray-400"><tr><th className="p-4 text-left">#</th>{columns.map(column=><th className="p-4 text-left" key={column.key||column.label}>{column.label}</th>)}</tr></thead><tbody>{rows.slice((current-1)*size,current*size).map((row,index)=><motion.tr key={row[rowKey]??index} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.2,delay:index*.03}} onClick={onRow?()=>onRow(row):undefined} className={`border-t border-[#262626] hover:bg-[#1a1a1a] ${onRow?'cursor-pointer':''}`}><td className="p-4 text-gray-500 font-mono text-xs">{(current-1)*size+index+1}</td>{columns.map(column=><td key={column.key||column.label} className="p-4 truncate" title={typeof row[column.key]==='string'?row[column.key]:undefined}>{column.render?column.render(row):row[column.key]??'?'}</td>)}</motion.tr>)}{!rows.length&&<tr><td colSpan={columns.length+1} className="p-12 text-center text-[10px] font-bold tracking-widest text-gray-500">{empty}</td></tr>}</tbody></table></div><div className="flex justify-between items-center mt-4 text-xs text-gray-400 gap-3 flex-wrap"><span>Showing {rows.length?(current-1)*size+1:0} &ndash; {Math.min(current*size,rows.length)} of {rows.length}</span><div className="flex items-center gap-3"><label className="manager-service-row-select-wrap"><span>Rows:</span><select className="manager-row-select" aria-label="Rows per page" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,15,20,50].map(val=><option key={val} value={val}>{val}</option>)}</select></label></div><div className="portal-pagination-buttons"><button aria-label="Previous page" disabled={current===1} onClick={()=>setPage(current-1)}>Prev</button>{pageRange.map((p,idx)=>p==='...'?<span key={`dots-${idx}`} className="manager-page-ellipsis">&hellip;</span>:<button key={p} aria-label={`Page ${p}`} aria-current={current===p?'page':undefined} className={`manager-page-num ${current===p?'is-active':''}`} onClick={()=>setPage(p)}>{p}</button>)}<button aria-label="Next page" disabled={current===totalPages} onClick={()=>setPage(current+1)}>Next</button></div></div></div>;}
export function Field({label,error,optional=false,children}){return <FieldValidationContext.Provider value={{label,optional,error}}><label className="block"><span className="block text-[10px] uppercase tracking-widest font-bold text-gray-400 mb-2">{String(label).replace(/\s*\*\s*$/,'')}{!optional&&<RequiredMark/>}</span>{children}{error&&<span className="field-validation-error" role="alert">{error}</span>}</label></FieldValidationContext.Provider>;}

function LegacyModal({title,children,onClose,direct=false}){useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const close=e=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',close);};},[onClose]);return <AnimatePresence initial={!direct}><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.2}} className="fixed inset-0 z-[100] bg-black/90 backdrop-blur-xl p-4 flex items-center justify-center"><motion.section role="dialog" aria-modal="true" aria-label={title} initial={{scale:.98}} animate={{scale:1}} transition={{duration:.2}} className="bg-[#141414] border border-[#333] rounded-xl p-6 w-full max-w-2xl max-h-[90vh] overflow-y-auto"><div className="flex justify-between gap-4 items-start mb-6"><h2 className="text-xl font-black uppercase tracking-tighter">{title}</h2><button aria-label="Close dialog" onClick={onClose}><i aria-hidden="true" className="fa-solid fa-xmark"/></button></div>{children}</motion.section></motion.div></AnimatePresence>;}


export function Badge({value}){
  const text=String(value||'?');
  const tone=getStatusTone(text);
  return <span className={`admin-state status-${tone}`}>{text}</span>;
}

export function DataTable(props){
  const themed=usePortalTheme();
  return themed?<PortalDataTable {...props}/>:<LegacyDataTable {...props}/>;
}
function PortalDataTable({rows,columns,rowKey='id',onRow,empty='NO RECORDS FOUND'}){
  const signature=rows.map(row=>row[rowKey]).join('|'),[paging,setPaging]=useState({signature,size:10,page:1});
  const {size}=paging,totalPages=Math.max(1,Math.ceil(rows.length/size)),current=Math.min(signature===paging.signature?paging.page:1,totalPages);
  return <div className="mt-6"><div className="admin-table-wrap portal-record-table"><table className="admin-table"><colgroup><col style={{width:'5%'}}/>{columns.map((column,i)=><col key={i} style={{width:column.width||`${95/columns.length}%`}}/>)}</colgroup><thead><tr><th>#</th>{columns.map(column=><th key={column.key||column.label}>{column.label}</th>)}</tr></thead><tbody>{rows.slice((current-1)*size,current*size).map((row,index)=><motion.tr key={row[rowKey]??index} initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.2,delay:index*.03}} onClick={onRow?()=>onRow(row):undefined} className={onRow?'cursor-pointer':''}><td className="admin-meta">{(current-1)*size+index+1}</td>{columns.map(column=>{const content=column.render?column.render(row):row[column.key]??'?';return <td key={column.key||column.label} title={typeof row[column.key]==='string'?row[column.key]:undefined}>{column.label==='Actions'?typedTableActions(content):/^(State|Status)$/i.test(column.label)&&typeof content==='string'?<Badge value={content}/>:content}</td>;})}</motion.tr>)}{!rows.length&&<tr><td colSpan={columns.length+1} className="admin-empty">{empty}</td></tr>}</tbody></table></div><RecordPagination total={rows.length} page={current} size={size} onPage={page=>setPaging({signature,size,page})} onSize={size=>setPaging({signature,size,page:1})}/></div>;
}

export function Modal({edit=false,...props}){
  const themed=usePortalTheme();
  return themed&&(edit||/^edit\b/i.test(props.title))?<PortalEditDrawer {...props}/>:<LegacyModal {...props}/>;
}
