import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import CrudPage from './CrudPage';
import {vehicleMakes,vehicleModels} from '../lib/fieldOptions';
import {api} from '../lib/api';
import {DataTable,Badge,SearchBar,money} from './DataUI';
export const vehicleFields=[{key:'licensePlate',label:'License plate'},{key:'make',label:'Make',options:form=>vehicleMakes(form.make),allowCustom:true,resets:['model'],choicePlaceholder:'Choose a manufacturer',customPlaceholder:'e.g. Toyota'},{key:'model',label:'Model',options:form=>vehicleModels(form.make,form.model),allowCustom:true,disabled:form=>!form.make,choicePlaceholder:'Choose a model for this make',customPlaceholder:'e.g. Corolla'},{key:'ownerName',label:'Owner name'},{key:'ownerContact',label:'Contact number'},{key:'manufactureYear',label:'Manufacture year',type:'number',integer:true,min:1900,max:new Date().getFullYear()+1,optional:true},{key:'fuelType',label:'Fuel type',options:['Petrol','Diesel','Hybrid','Electric'],optional:true},{key:'mileage',label:'Mileage (km)',type:'number',integer:true,min:0,optional:true},{key:'engineNumber',label:'Engine number',optional:true},{key:'chassisNumber',label:'Chassis number',optional:true}];
export function VehicleList({customer=false}){const [accounts,setAccounts]=useState([]),navigate=useNavigate();useEffect(()=>{if(!customer)api('/api/billing/customer-accounts').then(setAccounts).catch(()=>{});},[customer]);const root=customer?'/api/v1/customer/vehicles':'/api/workshop/vehicles/registry';return <CrudPage title={customer?'My garage':'Vehicle registry'} endpoint={root} rowsKey={customer?undefined:'vehicles'} fields={[...vehicleFields,...(!customer?[{key:'ownerUsername',label:'Customer account',optional:true,options:accounts.map(account=>({value:account.username,label:account.fullName+' (@'+account.username+')'}))}]:[])]} create={{url:customer?root:root+'/add'}} update={id=>({url:customer?root+'/'+id:root+'/update/'+id,method:customer?'PUT':'POST'})} remove={id=>({url:customer?root+'/'+id:root+'/delete/'+id,method:customer?'DELETE':'POST'})} columns={[{key:'licensePlate',label:'Plate',width:'15%',render:row=>customer?<Link className="text-brand-accent" to={'/customer/vehicles/'+row.id}>{row.licensePlate}</Link>:row.licensePlate},{key:'make',label:'Make',width:'15%'},{key:'model',label:'Model',width:'15%'},{key:'ownerName',label:'Owner',width:'20%'},{key:'ownerContact',label:'Contact',width:'15%'}]} extraActions={customer?(row)=><button aria-label="Book service" onClick={()=>navigate('/customer/book',{state:{vehicle:row}})}><i aria-hidden="true" className="fa-solid fa-calendar-plus text-blue-400"/></button>:undefined}/>;}
export function VehicleDetails(){const {id}=useParams(),navigate=useNavigate(),[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/api/v1/customer/vehicles/'+id).then(setData).catch(e=>setError(e.message));},[id]);if(!data)return <p role="alert">{error||'Loading vehicle...'}</p>;const {vehicle:v,serviceHistory}=data;return <div><Link to="/customer/vehicles" className="text-gray-400">Back to garage</Link><h1 className="text-3xl font-black my-6">{v.licensePlate} ? {v.make} {v.model}</h1><dl className="grid sm:grid-cols-3 gap-6 bg-brand-surface border border-brand-border p-6 rounded-xl">{vehicleFields.slice(3).map(field=><div key={field.key}><dt className="text-xs uppercase text-gray-400">{field.label}</dt><dd className="mt-2">{v[field.key]??'?'}</dd></div>)}</dl><button className="btn-accent rounded-full px-5 py-3 mt-6" onClick={()=>navigate('/customer/book',{state:{vehicle:v}})}>Book service for this vehicle</button><HistoryTable rows={serviceHistory}/></div>;}
export function HistoryTable({rows,customer=true}){return <DataTable rows={rows} columns={[{key:'referenceNumber',label:'Reference',width:'25%',render:row=>customer?<Link className="text-brand-accent" to={'/customer/track/'+row.referenceNumber}>{row.referenceNumber}</Link>:row.referenceNumber},{key:'licensePlate',label:'Vehicle',width:'15%'},{key:'serviceType',label:'Service',width:'25%'},{key:'serviceDate',label:'Date',width:'15%'},{label:'State',width:'15%',render:row=><Badge value={row.status}/>}]} />;}
export function ServiceHistory({customer=true}){const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState('');useEffect(()=>{api(customer?'/api/v1/customer/appointments':'/api/workshop/bookings').then(data=>setRows(customer?data:data.bookings)).catch(e=>setError(e.message));},[customer]);return <div><h1 className="text-3xl font-black uppercase mb-6">Service history</h1>{error&&<p role="alert" className="text-brand-accent">{error}</p>}<SearchBar onSearch={setQuery} status={status} setStatus={setStatus} statuses={[...new Set(rows.map(row=>row.status))]}/><HistoryTable customer={customer} rows={rows.filter(row=>(!status||row.status===status)&&JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))}/></div>;}
