import {useState} from 'react';
import {QuickDeck,money} from '../../components/DataUI';
import {ServiceHeader,ServiceFilters,ServiceTable} from './ManagerServiceUI';
import useInventoryWorkspace from './inventory/useInventoryWorkspace';
import {InventoryBadge,InventoryMessages} from './inventory/InventoryUI';
import InventoryForm from './inventory/InventoryForm';
import {CatalogCards,CatalogMedia} from './catalog/ManagerCatalogUI';
import {inventoryState} from './inventory/inventoryValues';

export default function ManagerSpareParts(){
  const workspace=useInventoryWorkspace('parts'),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[view,setView]=useState('table');
  const controls=<ServiceFilters label="Search parts" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} status={status} onStatus={setStatus} statuses={[...new Set(['In Stock','Low Stock',...workspace.rows.map(row=>inventoryState('parts',row.status))])]}><div className="manager-catalog-view" role="group" aria-label="Spare parts view">{[['table','Table'],['cards','Cards']].map(([value,label])=><button type="button" key={value} aria-pressed={view===value} className={view===value?'is-active':''} onClick={()=>setView(value)}>{label}</button>)}</div><button className="btn-accent manager-service-primary" onClick={()=>workspace.setSelected({stockQuantity:0,minStockWarning:5})}>Add part</button></ServiceFilters>;
  const rows=workspace.rows.filter(part=>(!status||inventoryState('parts',part.status)===status)&&[part.partName,part.category,part.supplier,'PRT-'+part.id].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase())));
  return <div className="manager-inventory manager-inventory-parts"><ServiceHeader kicker="Inventory infrastructure" title="Spare parts.">{controls}</ServiceHeader><InventoryMessages workspace={workspace}/><QuickDeck>{controls}</QuickDeck>{view==='table'?<ServiceTable name="Spare parts" rows={rows} loading={workspace.loading} columns={[
    {label:'Part ID',width:'9%',render:part=><span className="manager-service-id">PRT-{part.id}</span>},{key:'partName',label:'Part name',width:'28%',render:part=><strong>{part.partName}</strong>},{key:'category',label:'Category',width:'12%'},{key:'stockQuantity',label:'Stock',width:'7%'},{label:'Selling price',width:'12%',render:part=><span className="manager-inventory-price">Rs. {money(part.sellingPrice)}</span>},{label:'Status',width:'10%',render:part=><InventoryBadge kind="parts" value={part.status}/>},{label:'Actions',width:'17%',render:part=><div className="manager-service-actions"><button className="manager-service-action" onClick={()=>workspace.setSelected({...part})}>Edit</button><button className="manager-service-action" disabled={workspace.deleting!==null} onClick={()=>workspace.erase(part)}>{workspace.deleting===part.id?'Deleting…':'Delete'}</button></div>}
  ]}/>:<CatalogCards name="Spare parts" rows={rows} loading={workspace.loading}>{part=><><CatalogMedia name={part.partName} src={part.imageUrl}/><div className="manager-item-copy"><p className="manager-item-category"><span>{part.category}</span><span>PRT-{part.id}</span></p><h2>{part.partName}</h2><InventoryBadge kind="parts" value={part.status}/><div className="manager-item-meta"><strong>Rs. {money(part.sellingPrice)}</strong><span>{part.stockQuantity} in stock</span></div><p className="manager-item-secondary">Warning at {part.minStockWarning} units{part.supplier&&<> · {part.supplier}</>}</p><div className="manager-item-footer"><button className="manager-service-action" onClick={()=>workspace.setSelected({...part})}>Edit</button><button className="manager-service-action" disabled={workspace.deleting!==null} onClick={()=>workspace.erase(part)}>{workspace.deleting===part.id?'Deleting…':'Delete'}</button></div></div></>}</CatalogCards>}{workspace.selected&&<InventoryForm key={workspace.selected.id+'-'+workspace.selected.version} kind="parts" initial={workspace.selected} workspace={workspace}/>}</div>;
}
