import {Input,Select} from '../../components/Validation';
import {useState} from 'react';
import {QuickDeck,Field,money} from '../../components/DataUI';
import {ItemPhoto} from '../../components/ItemPhoto';
import {ServiceHeader,ServiceFilters} from './ManagerServiceUI';
import {InventoryBadge,InventoryModal} from './inventory/InventoryUI';
import {CatalogCards,CatalogMedia} from './catalog/ManagerCatalogUI';
import useCatalogWorkspace from './catalog/useCatalogWorkspace';

function OfferEditor({workspace,service}){
  const [form,setForm]=useState({...workspace.selected}),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),targets=workspace.data[service?'services':'spareParts'],target=targets.find(item=>String(item.id)===String(form.targetId)),price=Number(target?.[service?'estimatedCost':'sellingPrice']||0),discount=Number(form.discountPercentage)||0;
  const save=async event=>{event.preventDefault();if(busy)return;const issues={};if(!form.targetId)issues.targetId='Select an item';if(!Number.isFinite(Number(form.discountPercentage))||discount<=0||discount>100)issues.discountPercentage='Discount must be greater than 0 and at most 100%';setErrors(issues);if(Object.keys(issues).length)return;const body=new FormData();body.append('targetId',form.targetId);body.append('discountPercentage',discount);setBusy(true);try{await workspace.save(body);}catch(error){setErrors({form:error.message});}finally{setBusy(false);}};
  return <InventoryModal title={(form.id?'Edit ':'Create ')+(service?'service offer':'spare part offer')} kicker="Offers & promotions" variant="fuel" onClose={()=>workspace.setSelected(null)} busy={busy}><form noValidate onSubmit={save}><fieldset disabled={busy}><div className="manager-inventory-fields"><Field label={service?'Select service':'Select spare part'} error={errors.targetId}><div className="manager-inventory-select"><Select validationKey="targetId" className="input-dark" aria-label={service?'Select service':'Select spare part'} disabled={Boolean(form.id)} value={form.targetId||''} onChange={event=>{setForm({...form,targetId:event.target.value});setErrors({});}}><option value="">-- Choose {service?'Service':'Spare Part'} --</option>{targets.filter(item=>!service||item.active||item.id===form.targetId).map(item=><option key={item.id} value={item.id}>{item[service?'name':'partName']}{service?'':' - Rs. '+money(item.sellingPrice)}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div></Field><Field label="Discount percentage (%)" error={errors.discountPercentage}><Input validationKey="discountPercentage" className="input-dark" aria-label="Discount percentage" type="number" min="0.01" max="100" step=".01" placeholder="e.g. 15" value={form.discountPercentage??''} onChange={event=>{setForm({...form,discountPercentage:event.target.value});setErrors({});}}/></Field></div>{target&&<div className="manager-offer-preview"><ItemPhoto kind={service?'service':'part'} src={target.imageUrl} alt={target[service?'name':'partName']}/><div><strong>{target[service?'name':'partName']}</strong><span>Rs. {money(price*(1-Math.max(0,Math.min(100,discount))/100))}</span><p>Photo from {service?'service catalog':'spare parts inventory'}. Edit the item there to change its picture.</p></div></div>}</fieldset>{errors.form&&<p role="alert" className="manager-inventory-error">{errors.form}</p>}<footer><button type="button" className="manager-service-action" disabled={busy} onClick={()=>workspace.setSelected(null)}>Cancel</button><button type="submit" className="btn-accent manager-inventory-submit" disabled={busy}>{busy?'Saving…':form.id?'Save changes':'Create offer'}</button></footer></form></InventoryModal>;
}
export default function ManagerOffers({service=false}){
  const workspace=useCatalogWorkspace('/api/offers/'+(service?'services':'spare-parts'),service?'services':'parts'),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),targets=workspace.data[service?'services':'spareParts'];
  const items=workspace.data.offers.map(offer=>{const target=targets.find(item=>item.id===offer.targetId);return {...offer,name:target?.[service?'name':'partName']||'Unavailable item',target};});
  const rows=items.filter(item=>(!status||(item.active?'Active':'Inactive')===status)&&`${item.name} ${item.target?.category||''}`.toLowerCase().includes(query.toLowerCase()));
  const controls=<ServiceFilters label="Search offers" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} status={status} onStatus={setStatus} statuses={['Active','Inactive']}><button className="btn-accent manager-service-primary" onClick={()=>workspace.setSelected({})}>{service?'Create service offer':'Create offer'}</button></ServiceFilters>;
  return <div className="manager-catalog manager-inventory"><ServiceHeader kicker="Offers & promotions" title={service?'Service offers.':'Spare part offers.'}>{controls}</ServiceHeader><QuickDeck>{controls}</QuickDeck>{workspace.error&&<p className="manager-inventory-error" role="alert">{workspace.error}<button onClick={workspace.load}>Retry</button></p>}<CatalogCards rows={rows} loading={workspace.loading} name={service?'Service offers':'Spare part offers'}>{item=>{const price=Number(item.target?.[service?'estimatedCost':'sellingPrice']||0);return <><CatalogMedia kind={service?'service':'part'} src={item.target?.imageUrl} name={item.name} discount={item.discountPercentage}/><div className="manager-item-copy"><p className="manager-item-category">Target {service?'service':'spare part'}</p><h2>{item.name}</h2><InventoryBadge value={item.active?'Active':'Inactive'}/>{item.target&&<div className="manager-item-meta"><div><strong>Rs. {money(price*(1-item.discountPercentage/100))}</strong><del>Rs. {money(price)}</del></div><span>{item.target.category}</span></div>}<div className="manager-item-footer"><button className="manager-service-action" onClick={()=>workspace.setSelected(item)}>Edit</button><button className="manager-service-action" disabled={workspace.action!==null} onClick={()=>workspace.act(item,'toggle')}>{item.active?'Deactivate':'Activate'}</button><button className="manager-service-action" disabled={workspace.action!==null} onClick={()=>workspace.act(item,'delete')}>Delete</button></div></div></>;}}</CatalogCards>{workspace.selected&&<OfferEditor workspace={workspace} service={service}/>}</div>;
}
