import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState} from 'react';
import {api,requestKey,notice} from '../../lib/api';
import {useAuth} from '../../context/AuthContext';
import {CashierCardForm,CashierCardPending,CashierRecovery,loadCardSDK} from './CashierCardFlow';

const DeskContext=createContext(null);
async function fetchQuote(body){const response=await fetch((import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')+'/api/pos/quote',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||data.success===false){if(response.status===401)window.dispatchEvent(new Event('fuelcore:session-expired'));throw new Error(data.message||data.error||'Unable to update the receipt');}return data;}
export const useCashierPOS=()=>useContext(DeskContext);
export const cashAmount=value=>/^\d{1,9}(\.\d{1,2})?$/.test(String(value))&&Number.isFinite(Number(value));
export function CashierPOSProvider({children}){
  const {account}=useAuth(),storageKey='fuelcore.cashier.cart.'+account.username,attemptKey='fuelcore.cashier.attempt.'+account.username;
  const [savedAttempt]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(attemptKey)||'null');return saved?.key&&saved?.body?saved:null;}catch{return null;}});
  const [items,setItems]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'[]');return Array.isArray(saved)?saved.filter(row=>Number.isInteger(row.partId)&&row.partId>0&&/^\d{0,4}$/.test(String(row.quantity))).slice(0,100):[];}catch{return [];}});
  const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[mode,setMode]=useState('parts'),[service,setService]=useState(null),[method,setMethod]=useState('CASH'),[amount,setAmount]=useState(''),[cash,setCash]=useState(''),[qrConfirmed,setQRConfirmed]=useState(false),[remote,setRemote]=useState(null),[quoteError,setQuoteError]=useState(''),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[refresh,setRefresh]=useState(0);
  const saving=useRef(Boolean(savedAttempt)),attempt=useRef(savedAttempt),quoteRequest=useRef(0);
  const [recovery,setRecovery]=useState(savedAttempt),[recovering,setRecovering]=useState(false),[recoveryError,setRecoveryError]=useState('');
  const pendingKey='fuelcore.cashier.card.'+account.username;
  const [cardForm,setCardForm]=useState(false),[cardError,setCardError]=useState(''),[pending,setPending]=useState(()=>sessionStorage.getItem(pendingKey)||''),[cardState,setCardState]=useState(null);
  const cardFinished=useRef(false);
  const load=useCallback(async()=>{try{setProducts(await api('/api/pos/products'));setLoadError('');}catch(error){setLoadError(error.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();const update=()=>{if(!saving.current){load();setRefresh(value=>value+1);}};window.addEventListener('fuelcore:refresh',update);return()=>window.removeEventListener('fuelcore:refresh',update);},[load]);
  useEffect(()=>{sessionStorage.setItem(storageKey,JSON.stringify(items));},[storageKey,items]);
  const clearAttempt=()=>{attempt.current=null;sessionStorage.removeItem(attemptKey);};
  const invalidate=()=>{clearAttempt();setErrors({});setReceipt(null);};
  const editItems=(id,value)=>{invalidate();setItems(old=>{const found=old.find(item=>item.partId===id);if(found)return old.map(item=>item.partId===id?{...item,quantity:String(value)}:item);return [...old,{partId:id,quantity:String(value)}];});};
  const remove=id=>{invalidate();setItems(old=>old.filter(item=>item.partId!==id));};
  const cartErrors=items.reduce((result,row)=>{const product=products.find(p=>p.id===row.partId),quantity=Number(row.quantity);if(!product)result[row.partId]='This part is no longer available';else if(product.available===false)result[row.partId]='This part is inactive and cannot be sold';else if(!/^\d{1,4}$/.test(String(row.quantity))||quantity<1)result[row.partId]='Enter a whole quantity of at least 1';else if(quantity>product.stockQuantity)result[row.partId]='Only '+product.stockQuantity+' available';return result;},{});
  const signature=JSON.stringify([mode,service?.referenceNumber,items,products.map(p=>[p.id,p.price,p.stockQuantity]),refresh]);
  const payloadItems=useMemo(()=>items.map(row=>({partId:row.partId,quantity:Number(row.quantity)})),[items]);
  useEffect(()=>{const current=++quoteRequest.current;if(Object.keys(cartErrors).length||mode==='service'&&!service||!items.length&&!service)return;const timer=setTimeout(async()=>{try{const quote=await fetchQuote({referenceNumber:mode==='service'?service?.referenceNumber:null,items:payloadItems});if(current===quoteRequest.current){setRemote({signature,quote});setQuoteError('');}}catch(error){if(current===quoteRequest.current){setRemote(null);setQuoteError(error.message);}}},160);return()=>{clearTimeout(timer);quoteRequest.current++;};},[signature]);
  const base=mode==='service'?service:null;
  const added=items.map(row=>{const p=products.find(p=>p.id===row.partId);return {partId:row.partId,itemName:p?.partName||'Unavailable part',quantity:Number(row.quantity)||0,originalUnitPrice:p?.sellingPrice||0,unitPrice:p?.price||0,totalAmount:(p?.price||0)*(Number(row.quantity)||0),imageUrl:p?.imageUrl,existing:false};});
  const addedNet=added.reduce((sum,row)=>sum+row.totalAmount,0),addedOriginal=added.reduce((sum,row)=>sum+row.originalUnitPrice*row.quantity,0);
  const local={...(base||{}),invoice:base?.invoice,lines:[...(base?.lines||[]),...added],subtotal:(base?.subtotal||0)+addedOriginal,offerSavings:(base?.offerSavings||0)+addedOriginal-addedNet,recordedDiscount:base?.recordedDiscount||0,charges:base?.charges||0,total:(base?.total||0)+addedNet,paid:base?.paid||0,balance:(base?.balance||0)+addedNet,finalized:base?.finalized??true};
  const quote=remote?.signature===signature?remote.quote:local,ready=remote?.signature===signature&&!Object.keys(cartErrors).length&&(mode!=='service'||Boolean(service));
  const payAmount=mode==='parts'?quote.balance:amount===''?(quote.finalized?quote.balance:Math.max(0,Math.min((quote.invoice?.advanceAmountDue||0)-(quote.paid||0),quote.balance-.01))):Number(amount);
  const selectService=quote=>{invalidate();setService(quote);setMode('service');setAmount('');setCash('');setQRConfirmed(false);setRemote(null);};
  const change=(key,value)=>{invalidate();({mode:setMode,method:setMethod,amount:setAmount,cash:setCash,qrConfirmed:setQRConfirmed}[key])(value);if(key==='mode'){setAmount('');setCash('');setQRConfirmed(false);if(value==='parts')setService(null);}};
  const newSale=()=>{invalidate();setItems([]);setService(null);setMode('parts');setRemote(null);setAmount('');setCash('');setMethod('CASH');setQRConfirmed(false);setQuoteError('');};
  const validate=()=>{const issues={};if(!ready)issues.form=quoteError||'Wait for the receipt to update, and check item quantities';if(mode==='parts'&&!items.length)issues.form='Add at least one spare part';if(mode==='service'&&!service)issues.reference='Find and confirm a service reference';if(mode==='service'&&amount!==''&&!cashAmount(amount))issues.amount='Use a valid amount with at most two decimal places';if(!Number.isFinite(payAmount)||payAmount<0||payAmount>quote.balance+.001)issues.amount='Payment must be within the remaining balance';if(mode==='service'&&!quote.finalized&&payAmount>=quote.balance-.001&&quote.balance>0)issues.amount='Full settlement is available after service completion';if(payAmount===0&&!items.length)issues.amount='Enter a payment amount';if(method==='CASH'&&(!cashAmount(cash)||Number(cash)<payAmount))issues.cash='Cash received must cover this payment';if(method==='QR'&&!qrConfirmed)issues.qrConfirmed='Confirm the bank QR payment has been received';setErrors(issues);return !Object.keys(issues).length;};
  const completed=useCallback(async result=>{setItems([]);setService(null);setRemote(null);setMode('parts');setCash('');setAmount('');attempt.current=null;sessionStorage.removeItem(attemptKey);setReceipt(result);notice('Invoice and payment saved');await load();},[load,attemptKey]);
  const checkoutAttempt=()=>{if(!attempt.current){attempt.current={key:requestKey(),body:{referenceNumber:mode==='service'?service.referenceNumber:null,items:payloadItems,paymentMethod:method,amount:payAmount,cashTendered:method==='CASH'?Number(cash):null,quoteToken:quote.quoteToken,qrConfirmed}};sessionStorage.setItem(attemptKey,JSON.stringify(attempt.current));}return attempt.current;};
  const confirm=async()=>{if(saving.current||!validate())return;if(method==='CARD'){if(payAmount<=0)return setErrors({form:'Card payments require a positive payment amount'});setCardError('');setCardForm(true);return;}saving.current=true;setBusy(true);const sale=checkoutAttempt();let uncertain=false;try{await completed(await api('/api/pos/checkout',{method:'POST',headers:{'Idempotency-Key':sale.key},body:JSON.stringify(sale.body)}));}catch(error){setErrors({form:error.message});if(!error.status||error.status>=500){uncertain=true;setRecovery(sale);setRecoveryError(error.message);}else{clearAttempt();setRefresh(value=>value+1);await load();}}finally{if(!uncertain){saving.current=false;setBusy(false);}}};
  const retrySaved=async()=>{if(recovering||!attempt.current)return;setRecovering(true);setRecoveryError('');const sale=attempt.current;try{const recorded=await api('/api/pos/checkouts/'+encodeURIComponent(sale.key));if(recorded.completed){await completed(recorded);setRecovery(null);saving.current=false;setBusy(false);}else if(sale.body.paymentMethod==='CARD'){if(['FAILED','CANCELLED'].includes(recorded.state)){clearAttempt();setRecovery(null);saving.current=false;setBusy(false);setErrors({form:recorded.message});await load();}else{setRecovery(null);setCardForm(true);saving.current=false;setBusy(false);}}else{await completed(await api('/api/pos/checkout',{method:'POST',headers:{'Idempotency-Key':sale.key},body:JSON.stringify(sale.body)}));setRecovery(null);saving.current=false;setBusy(false);}}catch(error){if(error.status&&error.status<500){clearAttempt();setRecovery(null);saving.current=false;setBusy(false);setErrors({form:error.message});setRefresh(value=>value+1);await load();}else setRecoveryError(error.message);}finally{setRecovering(false);}};
  const checkCard=useCallback(async()=>{if(!pending||cardFinished.current)return;try{const result=await api('/api/pos/card/'+encodeURIComponent(pending));if(cardFinished.current)return;setCardState(result);if(result.completed){cardFinished.current=true;sessionStorage.removeItem(pendingKey);setPending('');saving.current=false;setBusy(false);await completed(result);}else if(['CANCELLED','FAILED'].includes(result.state)){cardFinished.current=true;sessionStorage.removeItem(pendingKey);setPending('');saving.current=false;setBusy(false);clearAttempt();setErrors({form:result.message});setRefresh(value=>value+1);await load();}}catch(error){setCardState(old=>({...old,message:error.message+' Check payment status before taking another payment.'}));}},[pending,pendingKey,load,completed]);
  useEffect(()=>{if(!pending)return;saving.current=true;setBusy(true);checkCard();const timer=setInterval(checkCard,2500);return()=>clearInterval(timer);},[pending,checkCard]);
  const startCard=async billing=>{if(saving.current)return;saving.current=true;setBusy(true);setCardError('');try{const settings=await api('/api/pos/card/configuration');if(!settings.configured)throw new Error('Card payments are not configured for this station yet. Use Cash or QR, or contact the administrator.');await loadCardSDK();const sale=checkoutAttempt();const result=await api('/api/pos/card/start',{method:'POST',headers:{'Idempotency-Key':sale.key},body:JSON.stringify({checkout:sale.body,billing})});if(result.completed){await completed(result);setCardForm(false);saving.current=false;setBusy(false);return;}if(!result.saleId)throw new Error('The card checkout could not be prepared');sessionStorage.setItem(pendingKey,result.saleId);cardFinished.current=false;setPending(result.saleId);setCardForm(false);setCardState(result);if(result.payment){window.payhere.onCompleted=()=>setCardState(old=>({...old,message:'Waiting for the signed payment notification...'}));const cancel=async()=>{try{const cancelled=await api('/api/pos/card/'+encodeURIComponent(result.saleId)+'/cancel-unprocessed',{method:'POST'});setCardState(cancelled);}catch(error){setCardState(old=>({...old,message:error.message+' Verify payment status before retrying.'}));}};window.payhere.onDismissed=cancel;window.payhere.onError=cancel;window.payhere.startPayment(result.payment);}}catch(error){setCardError(error.message);if(!sessionStorage.getItem(pendingKey)){if(attempt.current&&(!error.status||error.status>=500)){setRecovery(attempt.current);setRecoveryError(error.message);setCardForm(false);}else{clearAttempt();saving.current=false;setBusy(false);setRefresh(value=>value+1);load();}} }};
  return <DeskContext.Provider value={{products,loading,loadError,load,items,cartErrors,editItems,remove,mode,service,selectService,method,amount,cash,qrConfirmed,change,quote,ready,quoteError,refreshQuote:()=>{attempt.current=null;setRefresh(value=>value+1);load();},payAmount,errors,busy,receipt,newSale,confirm}}>{children}{(cardForm||pending||recovery)&&<div className="manager-portal cashier-portal cashier-card-overlay">{cardForm&&<CashierCardForm amount={attempt.current?.body.amount??payAmount} busy={busy} error={cardError} onClose={()=>{setCardForm(false);if(attempt.current){setRecovery(attempt.current);saving.current=true;setBusy(true);}}} onConfirm={startCard}/ >}{pending&&<CashierCardPending state={cardState?.state} message={cardState?.message} onRefresh={checkCard}/>}{recovery&&!pending&&<CashierRecovery busy={recovering} error={recoveryError} card={recovery.body.paymentMethod==='CARD'} onRetry={retrySaved}/>}</div>}</DeskContext.Provider>;
}
