import {Input,RequiredMark} from '../../components/Validation';
import {useState} from 'react';
import {CashierModal} from './CashierUI';
import {validateFields} from '../../lib/validation';
import {money} from '../../components/DataUI';

let sdk;
export function loadCardSDK(){if(window.payhere)return Promise.resolve();if(!sdk)sdk=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.payhere.lk/lib/payhere-2.0.js';script.async=true;script.onload=()=>window.payhere?resolve():reject(new Error('Card gateway did not load'));script.onerror=()=>{sdk=null;script.remove();reject(new Error('Cannot connect to the card gateway. Retry when the connection is available.'));};document.head.appendChild(script);});return sdk;}
export function CashierCardForm({amount,busy,error,onClose,onConfirm}){
 const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',address:'',city:'',country:'Sri Lanka'}),[errors,setErrors]=useState({});
 const labels={firstName:'First name',lastName:'Last name',email:'Email',phone:'Phone',address:'Billing address',city:'City',country:'Country'},limits={firstName:60,lastName:60,email:120,phone:20,address:200,city:80,country:80};
 const submit=e=>{e.preventDefault();const trimmed=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value.trim()]));const issues=validateFields(Object.entries(labels).map(([key,label])=>({key,label,maxLength:limits[key]})),trimmed);for(const [key,value] of Object.entries(trimmed))if(!value||/[<>\u0000-\u001f]/.test(value))issues[key]='Enter a valid '+labels[key].toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(trimmed.email))issues.email='Enter a valid email';setErrors(issues);if(!Object.keys(issues).length)onConfirm(trimmed);};
 return <CashierModal title="Card billing details" onClose={onClose} busy={busy}><p className="cashier-note">Rs. {money(amount)} · Card details are entered in PayHere's secure checkout. These billing details are used only for this payment and do not create a customer account.</p><form className="cashier-card-form" noValidate onSubmit={submit}>{Object.entries(labels).map(([key,label])=><label key={key}><span>{label}<RequiredMark/></span><Input required validationKey={key} aria-label={label} aria-describedby={errors[key]?'cashier-card-error-'+key:undefined} className="input-dark" maxLength={limits[key]} autoComplete={{firstName:'given-name',lastName:'family-name',email:'email',phone:'tel',address:'street-address',city:'address-level2',country:'country-name'}[key]} inputMode={key==='phone'?'tel':key==='email'?'email':undefined} value={form[key]} disabled={busy} aria-invalid={Boolean(errors[key])} onChange={e=>{setForm({...form,[key]:e.target.value});setErrors({...errors,[key]:''});}}/>{errors[key]&&<span id={'cashier-card-error-'+key} role="alert" className="cashier-error">{errors[key]}</span>}</label>)}{error&&<p role="alert" className="cashier-error">{error}</p>}<button disabled={busy} className="btn-accent">{busy?'Opening secure checkout...':'Pay by card'}</button></form></CashierModal>;
}
export function CashierCardPending({state,message,onRefresh}){return <CashierModal title={state==='REVIEW'?'Payment needs verification':'Awaiting card confirmation'} busy onClose={()=>{}}><p className="cashier-note">{message||'Wait for confirmation from PayHere. Closing the gateway window does not prove whether payment was collected.'}</p><p>The invoice is paid only after the server verifies the gateway notification. Do not collect the same payment again.</p><button className="btn-accent" onClick={onRefresh}>Check payment status</button></CashierModal>;}
export function CashierRecovery({busy,error,card,onRetry}){return <CashierModal title="Recover checkout" busy onClose={()=>{}}><p className="cashier-note">The previous checkout's result was not received. Check it before starting another sale. Retrying uses the same checkout reference.</p>{error&&<p role="alert" className="cashier-error">{error}</p>}<button className="btn-accent" disabled={busy} onClick={onRetry}>{busy?'Checking...':card?'Check or resume card checkout':'Check and retry saved checkout'}</button></CashierModal>;}
