import {Input,RequiredMark} from '../../components/Validation';
import {useState} from 'react';
import {useSearchParams,Link} from 'react-router-dom';
import {api} from '../../lib/api';
import {CashierPhoto as ItemPhoto} from './CashierPhoto';
import {money} from '../../components/DataUI';
import {downloadReceipt} from '../../components/BillingPages';
import {useCashierPOS} from './CashierPOSContext';
import {CashierModal,CashierState} from './CashierUI';

export function PartCard({part,quantity=0,onAdd,disabled=false}){
 return <article className={'cashier-product '+(quantity?'is-selected':'')}><div className="cashier-product-photo"><ItemPhoto src={part.imageUrl} alt={part.partName}/>{part.discountPercentage>0&&<span className="cashier-offer-mark">{part.discountPercentage}% OFF</span>}{(part.available===false||part.stockQuantity<=0)&&<span className="cashier-stock-mark">{part.available===false?'Inactive':'Out of stock'}</span>}</div><div className="cashier-product-copy"><p>{part.category||'Essentials'}</p><h2>{part.partName}</h2><small>PRT-{part.id} - {part.stockQuantity} in stock</small><div className="cashier-product-bottom"><div>{part.discountPercentage>0&&<del>Rs. {money(part.sellingPrice)}</del>}<strong>Rs. {money(part.price)}</strong></div><button className="cashier-add" disabled={disabled||part.available===false||part.stockQuantity<=0||quantity>=part.stockQuantity} aria-label={'Add '+part.partName} onClick={onAdd}><i aria-hidden="true" className="fa-solid fa-plus"/>{quantity>0&&<span>{quantity}</span>}</button></div></div></article>;
}
function ReferenceFinder({initial='',onClose}){
 const desk=useCashierPOS(),[draft,setDraft]=useState(initial),[found,setFound]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const find=async event=>{event.preventDefault();setFound(null);if(!/^[A-Za-z0-9-]{3,64}$/.test(draft.trim()))return setError('Use the service reference number, with letters, numbers and hyphens only');setBusy(true);setError('');try{setFound(await api('/api/pos/reference/'+encodeURIComponent(draft.trim())));}catch(error){setError(error.message);}finally{setBusy(false);}};
 return <CashierModal title="Find service invoice" onClose={onClose} busy={busy}><p className="cashier-muted">Search the appointment reference. Confirm its details to add the service to this receipt.</p><form noValidate onSubmit={find} className="cashier-reference-search"><label>Service reference<RequiredMark/><Input required validationKey="referenceNumber" aria-label="Service reference" autoComplete="off" maxLength={64} className="input-dark" value={draft} aria-invalid={Boolean(error)} onChange={event=>{setDraft(event.target.value);setError('');setFound(null);}} placeholder="e.g. REF-12345678"/></label><button disabled={busy} className="btn-accent">{busy?'Searching...':'Search reference'}</button></form>{error&&<p className="cashier-error" role="alert">{error}</p>}{found&&<section className="cashier-reference-result"><CashierState value={found.booking.status}/><h3>{found.booking.serviceType}</h3><dl>{[['Reference',found.referenceNumber],['Existing invoice',found.invoice?.invoiceNumber||'Created on confirmation'],['Vehicle',found.booking.licensePlate],['Balance','Rs. '+money(found.balance)],['Due date',found.dueDate||'Payment period starts at service completion']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button className="btn-accent" onClick={()=>{desk.selectService(found);onClose();}}>Confirm service</button></section>}</CashierModal>;
}
function ReceiptPanel(){
 const desk=useCashierPOS(),{quote:q,receipt:r}=desk,[downloadError,setDownloadError]=useState('');
 if(r){const inv=r.invoice;return <aside className="cashier-receipt"><header><div><p>Sale recorded</p><h2>Receipt</h2></div><CashierState value={inv.status}/></header><strong className="cashier-receipt-number">{inv.invoiceNumber}</strong>{inv.referenceNumber&&<div className="cashier-service-summary"><strong>Service reference: {inv.referenceNumber}</strong><small>Customer type: {inv.customerType?.replaceAll('_',' ')||'GUEST CUSTOMER'}</small></div>}<dl className="cashier-receipt-totals">{[['Payment recorded',r.paymentAmount],['Saved with offers',r.offerSavings],['Invoice total',inv.netTotalWithPenalty],['Remaining balance',inv.balanceDue],['Change',r.changeDue]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>Rs. {money(value)}</dd></div>)}</dl><p className="cashier-muted">Issued {inv.invoiceDate} - Due {inv.dueDate||'After service completion'}</p><div className="cashier-receipt-actions"><button className="btn-accent" onClick={desk.newSale}>New invoice</button><Link className="cashier-secondary" to={'/dashboard/invoices/'+inv.id}>View invoice</Link><button className="cashier-secondary" onClick={async()=>{try{await downloadReceipt('/api/billing/invoices/'+inv.id+'/receipt',inv.invoiceNumber+'.pdf');}catch(error){setDownloadError(error.message);}}}>Download receipt</button></div>{downloadError&&<p className="cashier-error" role="alert">{downloadError}</p>}</aside>;}
 return <aside className="cashier-receipt"><header><div><p>{desk.mode==='service'?'Service invoice':'Guest spare-part sale'}</p><h2>Order summary</h2></div><button className="cashier-secondary" disabled={desk.busy} onClick={desk.newSale}>New invoice</button></header>
 {desk.service&&desk.mode==='service'&&<div className="cashier-service-summary"><strong>{desk.service.referenceNumber}</strong><span>Vehicle: {desk.service.booking.licensePlate}</span><small>Customer type: {q.customerType?.replaceAll('_',' ')||desk.service.customerType.replaceAll('_',' ')}</small><small>{desk.service.invoice?.invoiceNumber||'Invoice created on confirmation'}</small><small>Due: {q.dueDate||'After service completion'}</small></div>}
 {desk.mode==='parts'&&<p className="cashier-muted">{q.issueDate?'Issued '+q.issueDate+' - Due '+q.dueDate:'Spare-part invoices are due on their issue date.'}</p>}<div className="cashier-receipt-items" aria-live="polite">{!q.lines.length&&<div className="cashier-cart-empty"><i aria-hidden="true" className="fa-solid fa-basket-shopping"/><p>Select spare parts to start a new invoice.</p></div>}{q.lines.map((row,index)=><div className="cashier-receipt-line" key={(row.existing?'existing-':'new-')+row.partId+'-'+index}><ItemPhoto kind={row.partId?'part':'service'} src={row.imageUrl} alt=""/><div className="cashier-line-copy"><strong>{row.itemName}</strong><span>Rs. {money(row.unitPrice)} / unit</span>{row.existing?<small>{row.quantity} already invoiced</small>:<><div className="cashier-quantity"><button disabled={desk.busy||row.quantity<=1} aria-label={'Decrease '+row.itemName} onClick={()=>desk.editItems(row.partId,row.quantity-1)}>-</button><Input showValidation={false} validationKey="quantity" validation={{integer:true,min:1,max:Math.min(desk.products.find(p=>p.id===row.partId)?.stockQuantity||0,9999)}} aria-label={'Quantity for '+row.itemName} inputMode="numeric" maxLength={4} value={desk.items.find(i=>i.partId===row.partId)?.quantity??''} aria-invalid={Boolean(desk.cartErrors[row.partId])} onChange={event=>{if(/^\d{0,4}$/.test(event.target.value))desk.editItems(row.partId,event.target.value);}}/><button disabled={desk.busy||row.quantity>=(desk.products.find(p=>p.id===row.partId)?.stockQuantity||0)} aria-label={'Increase '+row.itemName} onClick={()=>desk.editItems(row.partId,row.quantity+1)}>+</button></div>{desk.cartErrors[row.partId]&&<p className="cashier-error" role="alert">{desk.cartErrors[row.partId]}</p>}</>}</div><div className="cashier-line-total"><strong>Rs. {money(row.totalAmount)}</strong>{!row.existing&&<button disabled={desk.busy} className="cashier-remove" onClick={()=>desk.remove(row.partId)}>Remove</button>}</div></div>)}</div>
 <dl className="cashier-receipt-totals"><div><dt>Subtotal</dt><dd>Rs. {money(q.subtotal)}</dd></div>{q.offerSavings>0&&<div className="cashier-saved"><dt>Saved with offers</dt><dd>- Rs. {money(q.offerSavings)}</dd></div>}{q.recordedDiscount>0&&<div><dt>Recorded invoice discount</dt><dd>- Rs. {money(q.recordedDiscount)}</dd></div>}{q.charges>0&&<div><dt>Daily charges</dt><dd>Rs. {money(q.charges)}</dd></div>}{q.paid>0&&<div><dt>Previously paid</dt><dd>Rs. {money(q.paid)}</dd></div>}<div className="cashier-bill-total"><dt>Balance</dt><dd>Rs. {money(q.balance)}</dd></div></dl>
 {desk.mode==='service'&&!q.finalized&&desk.service&&<p className="cashier-note">Advance or partial payments are available. Full settlement and the payment period start after service completion.</p>}
 <fieldset disabled={desk.busy} className="cashier-payment-fields"><legend>Payment method</legend><div className="cashier-payment-methods">{[['CASH','Cash','fa-money-bill-wave'],['CARD','Card','fa-credit-card'],['QR','QR','fa-qrcode']].map(([value,label,icon])=><button type="button" key={value} aria-pressed={desk.method===value} onClick={()=>desk.change('method',value)}><i aria-hidden="true" className={'fa-solid '+icon}/>{label}</button>)}</div>
 {desk.mode==='service'&&<label>Payment amount (Rs.)<Input validationKey="amount" className="input-dark" inputMode="decimal" aria-invalid={Boolean(desk.errors.amount)} placeholder={money(desk.payAmount)} value={desk.amount} onChange={event=>{if(/^\d{0,9}(\.\d{0,2})?$/.test(event.target.value))desk.change('amount',event.target.value);}}/>{desk.errors.amount&&<span className="cashier-error" role="alert">{desk.errors.amount}</span>}</label>}
 {desk.method==='CASH'&&<label>Cash received (Rs.)<RequiredMark/><Input required validationKey="cashTendered" aria-label="Cash received (Rs.)" className="input-dark" inputMode="decimal" aria-invalid={Boolean(desk.errors.cash)} value={desk.cash} placeholder="0.00" onChange={event=>{if(/^\d{0,9}(\.\d{0,2})?$/.test(event.target.value))desk.change('cash',event.target.value);}}/>{desk.errors.cash&&<span className="cashier-error" role="alert">{desk.errors.cash}</span>}<small>Change: Rs. {money(Math.max(0,(Number(desk.cash)||0)-desk.payAmount))}</small></label>}
 {desk.method==='QR'&&<label className="cashier-qr-confirm"><Input type="checkbox" checked={desk.qrConfirmed} onChange={event=>desk.change('qrConfirmed',event.target.checked)}/>I have verified receipt of the bank QR payment.{desk.errors.qrConfirmed&&<span className="cashier-error" role="alert">{desk.errors.qrConfirmed}</span>}</label>}
 {desk.method==='CARD'&&<p className="cashier-note">Card payment will open the secure payment gateway. The receipt is settled only after server confirmation.</p>}
 </fieldset>{desk.quoteError&&<p className="cashier-error" role="alert">{desk.quoteError} <button onClick={desk.refreshQuote}>Refresh receipt</button></p>}{desk.errors.form&&<p className="cashier-error" role="alert">{desk.errors.form}</p>}<button className="btn-accent cashier-confirm" disabled={desk.busy||!desk.ready||Boolean(Object.keys(desk.cartErrors).length)} onClick={desk.confirm}>{desk.busy?'Saving...':desk.method==='CARD'?'Continue to card payment':'Confirm invoice'}<i aria-hidden="true" className="fa-solid fa-arrow-right"/></button>{!desk.ready&&q.lines.length>0&&!desk.quoteError&&<small className="cashier-muted">Updating receipt...</small>}
 </aside>;
}
export default function CashierDashboard(){
 const desk=useCashierPOS(),[params,setParams]=useSearchParams(),[finder,setFinder]=useState(Boolean(params.get('reference'))),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1);
 const categories=[...new Set(desk.products.map(p=>p.category||'Essentials'))],products=desk.products.filter(p=>(!category||p.category===category)&&[p.partName,p.category,p.id,'PRT-'+p.id].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase()))),pages=Math.max(1,Math.ceil(products.length/12)),current=Math.min(page,pages),settled=desk.mode==='service'&&desk.service?.invoice?.settledTotal!=null;
 return <div className="cashier-desk"><div className="cashier-heading"><div><p>Counter sales</p><h1>Point of sale.</h1><span>Spare parts, service invoices and payments at one counter.</span></div><button className={'cashier-secondary '+(desk.mode==='service'?'is-active':'')} disabled={desk.busy} onClick={()=>{desk.change('mode','service');setFinder(true);}}><i aria-hidden="true" className="fa-solid fa-wrench"/>Service</button>{desk.mode==='service'&&<button className="cashier-secondary" disabled={desk.busy} onClick={()=>desk.change('mode','parts')}>Spare-part sale</button>}</div>
 <div className="cashier-pos-columns"><section className="cashier-product-area"><div className="cashier-categories" aria-label="Part categories"><button aria-pressed={!category} onClick={()=>{setCategory('');setPage(1);}}>All parts<span>{desk.products.length}</span></button>{categories.map(value=><button key={value} aria-pressed={category===value} onClick={()=>{setCategory(value);setPage(1);}}>{value}<span>{desk.products.filter(p=>p.category===value).length}</span></button>)}</div><div className="cashier-products-toolbar"><h2>Spare parts <span>{products.length} items</span></h2><form noValidate className="manager-service-search" onSubmit={event=>{event.preventDefault();setQuery(draft.trim());setPage(1);}}><Input className="input-dark" maxLength={150} value={draft} onChange={event=>setDraft(event.target.value)} aria-label="Search spare parts" placeholder="Search name, category or item #"/>{draft&&<button type="button" aria-label="Clear product search" onClick={()=>{setDraft('');setQuery('');setPage(1);}}><i aria-hidden="true" className="fa-solid fa-xmark"/></button>}<button aria-label="Search parts"><i aria-hidden="true" className="fa-solid fa-magnifying-glass"/></button></form></div>
 {desk.loadError&&<p className="cashier-error" role="alert">{desk.loadError} <button onClick={desk.load}>Retry</button></p>}{desk.loading?<p className="cashier-empty">Loading spare parts...</p>:<div className="cashier-product-grid">{products.slice((current-1)*12,current*12).map(part=><PartCard key={part.id} part={part} quantity={Number(desk.items.find(row=>row.partId===part.id)?.quantity)||0} disabled={desk.busy||settled} onAdd={()=>desk.editItems(part.id,(Number(desk.items.find(row=>row.partId===part.id)?.quantity)||0)+1)}/>)}</div>}{!desk.loading&&!products.length&&<p className="cashier-empty">No spare parts match this search.</p>}<nav className="cashier-card-pagination" aria-label="Spare parts pagination"><span>{products.length?`${(current-1)*12+1}-${Math.min(current*12,products.length)}`:'0'} of {products.length}</span><button disabled={current===1} onClick={()=>setPage(current-1)}>Prev</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>
 </section><ReceiptPanel/></div>{finder&&<ReferenceFinder initial={params.get('reference')||''} onClose={()=>{setFinder(false);if(params.has('reference')){params.delete('reference');setParams(params,{replace:true});}}}/>}</div>;
}
