import {serviceCategories} from '../../../lib/fieldOptions';
import AdminCatalog from '../AdminCatalog';
import {useAuth} from '../../../context/AuthContext';
import ManagerServiceCatalog from '../../manager/ManagerServiceCatalog';
import CrudPage from '../../../components/CrudPage';
import {api} from '../../../lib/api';
import {Badge,money} from '../../../components/DataUI';
function LegacyServiceCatalog(){const root='/api/services';return <CrudPage title="Service catalog" endpoint={root} rowsKey="services" statusKey="active" defaults={{estimatedDuration:'1 Hour',popular:false,icon:'fa-wrench'}} create={{url:root+'/add'}} update={id=>({url:root+'/update/'+id})} remove={id=>({url:root+'/delete/'+id,method:'POST'})} fields={[{key:'name',label:'Service name'},{key:'category',label:'Category',options:serviceCategories,allowCustom:true},{key:'estimatedCost',label:'Cost (LKR)',type:'number',min:0},{key:'estimatedDuration',label:'Duration',options:['30 Minutes','1 Hour','2 Hours','3 Hours','4 Hours']},{key:'icon',label:'Icon class',optional:true},{key:'shortDescription',label:'Description',type:'textarea',optional:true},{key:'popular',label:'Popular service',type:'boolean',options:[{value:'true',label:'Yes'},{value:'false',label:'No'}]}]} columns={[{key:'name',label:'Service',width:'25%'},{key:'category',label:'Category',width:'15%'},{key:'estimatedDuration',label:'Duration',width:'15%'},{label:'Cost LKR',width:'15%',render:s=>money(s.estimatedCost)},{label:'State',width:'10%',render:s=><Badge value={s.active?'Active':'Inactive'}/> }]} extraActions={(row,load)=><button aria-label="Toggle active service" onClick={async()=>{await api(root+'/toggle/'+row.id,{method:'POST'});load();}}><i aria-hidden="true" className="fa-solid fa-power-off text-blue-400"/></button>}/>;}

export default function ServiceCatalog(){const {account}=useAuth();if(account?.role==='ROLE_ADMIN')return <AdminCatalog/>;return account?.role==='ROLE_MANAGER'?<ManagerServiceCatalog/>:<LegacyServiceCatalog/>;}
