import {Input,Select} from '../../../components/Validation';
import {useState} from 'react';
import {Badge,money,QuickDeck} from '../../../components/DataUI';
import {ServiceTable} from '../../manager/ManagerServiceUI';
import {useFuelOperations} from './FuelOperationsContext';
import FuelPageShell from './FuelPageShell';

export default function FuelPumpHistory(){
  const {data}=useFuelOperations(),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[pumpId,setPumpId]=useState('');
  const reset=()=>{setDraft('');setQuery('');setStatus('');setPumpId('');};
  const controls=<div className="manager-fuel-history-controls"><form noValidate className="manager-service-search" onSubmit={event=>{event.preventDefault();setQuery(draft.trim());}}><Input className="input-dark" aria-label="Search pump history" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Search date, pump or fuel..."/>{draft&&<button type="button" aria-label="Clear search text" onClick={()=>{setDraft('');setQuery('');}}><i aria-hidden="true" className="fa-solid fa-xmark"/></button>}<button type="submit" aria-label="Search"><i aria-hidden="true" className="fa-solid fa-magnifying-glass"/></button></form><Select className="input-dark" aria-label="Filter status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All Status</option><option>Active</option><option>Inactive</option></Select><Select className="input-dark" aria-label="Filter pump" value={pumpId} onChange={event=>setPumpId(event.target.value)}><option value="">All pumps</option>{data?.pumps.map(pump=><option value={pump.id} key={pump.id}>{pump.pumpName}</option>)}</Select>{(draft||query||status||pumpId)&&<button className="manager-service-action" onClick={reset}>Reset filters</button>}</div>;
  const history=data?.salesHistory.filter(row=>row.confirmed&&(!status||row.pumpStatus===status)&&(!pumpId||String(row.pump.id)===pumpId)&&`${row.saleDate} ${row.pump.pumpName} ${row.pump.fuelType} ${row.deactivationReason||''}`.toLowerCase().includes(query.toLowerCase()))||[];
  return <FuelPageShell section="pump-history" title="Individual pump history." description="Review each pump's confirmed figures and inactive periods.">{data&&<section id="pump-history">{controls}<QuickDeck>{controls}</QuickDeck><ServiceTable name="Pump history" rows={history} columns={[{key:'saleDate',label:'Date',width:'12%'},{label:'Pump / Fuel',width:'22%',render:row=><><strong>{row.pump.pumpName}</strong><small className="manager-fuel-cell-detail">{row.pump.fuelType}</small></>},{key:'litersSold',label:'Litres',width:'9%',render:row=>money(row.litersSold)},{key:'expectedAmount',label:'Expected (LKR)',width:'12%',render:row=>money(row.expectedAmount)},{key:'collectedAmount',label:'Collected (LKR)',width:'12%',render:row=>money(row.collectedAmount)},{key:'difference',label:'Difference (LKR)',width:'12%',render:row=>money(row.difference)},{key:'pumpStatus',label:'State / Reason',width:'16%',render:row=><><Badge value={row.pumpStatus}/>{row.deactivationReason&&<small className="manager-fuel-cell-detail">{row.deactivationReason}</small>}</>}]} /></section>}</FuelPageShell>;
}
