import {Input,TextArea} from '../../components/Validation';
import {useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useNotifications} from '../../context/NotificationContext';
import {api,notice,confirmAction} from '../../lib/api';
import {Field,QuickDeck} from '../../components/DataUI';
import {AdminHeader,AdminFilters,AdminTable,AdminState,dateText} from './AdminUI';
export default function AdminNotifications(){
 const feed=useNotifications(),navigate=useNavigate(),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[form,setForm]=useState({title:'',message:'',roles:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),pending=useRef(false);
 const open=async row=>{try{await feed.mark(row.id);if(row.actionUrl)navigate(row.actionUrl);}catch{}};
 const send=async event=>{event.preventDefault();if(pending.current)return;setError('');if(!form.title.trim()||!form.message.trim())return setError('Title and message are required');pending.current=true;setBusy(true);try{await api('/api/v1/notifications/announcements',{method:'POST',body:JSON.stringify(form)});setForm({title:'',message:'',roles:[]});notice('Announcement sent');}catch(error){setError(error.message);}finally{pending.current=false;setBusy(false);}};
 const rows=feed.rows.filter(row=>(!status||row.status===status)&&`${row.title} ${row.message}`.toLowerCase().includes(query.toLowerCase())),controls=<AdminFilters label="Search notifications" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} filters={[{label:'Filter status',all:'All status',value:status,change:setStatus,options:['Unread','Read']}]} onReset={()=>{setDraft('');setQuery('');setStatus('');}}><button className="btn-accent" disabled={!feed.unread} onClick={()=>feed.all().catch(()=>{})}>Mark all read</button></AdminFilters>;
 return <div><AdminHeader title="Notifications." kicker={`${feed.unread} unread messages`}/>{feed.error&&<p role="alert" className="admin-error">{feed.error} <button onClick={feed.refresh}>Retry</button></p>}{controls}<QuickDeck>{controls}</QuickDeck><AdminTable name="Notifications" rows={rows} columns={[{label:'Notification',width:'21%',render:row=><button className="font-bold text-left" onClick={()=>open(row)}>{row.title}</button>},{label:'Message',width:'32%',render:row=><details className="admin-log-details"><summary>{row.message}</summary><p>{row.message}</p></details>},{label:'Received',width:'16%',render:row=><span className="admin-meta">{dateText(row.createdDate,true)}</span>},{label:'Status',width:'9%',render:row=><AdminState value={row.status}/>},{label:'Actions',width:'18%',render:row=><div className="admin-actions"><button className="admin-action" disabled={row.status==='Read'} onClick={()=>feed.mark(row.id).catch(()=>{})}>Mark read</button><button className="admin-action" onClick={async()=>{if(await confirmAction('Delete this notification?'))feed.remove(row.id).catch(()=>{});}}>Delete</button></div>}]}/><section className="admin-announcement"><h2>Send announcement</h2><form noValidate onSubmit={send}><fieldset disabled={busy} className="admin-editor-fields"><Field label="Title"><Input validationKey="title" className="input-dark" maxLength={150} value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></Field><Field label="Message"><TextArea validationKey="message" className="input-dark" rows={3} maxLength={255} value={form.message} onChange={event=>setForm({...form,message:event.target.value})}/></Field><fieldset className="admin-announcement-roles"><legend>Roles (leave empty to notify all roles)</legend>{['ADMIN','MANAGER','CASHIER','MECHANIC','CUSTOMER'].map(role=><label key={role}><Input type="checkbox" checked={form.roles.includes(role)} onChange={event=>setForm({...form,roles:event.target.checked?[...form.roles,role]:form.roles.filter(item=>item!==role)})}/>{role}</label>)}</fieldset></fieldset>{error&&<p role="alert" className="admin-error">{error}</p>}<button disabled={busy} className="btn-accent">{busy?'Sending...':'Send announcement'}</button></form></section></div>;
}
