import {Input,Select} from '../../components/Validation';
import {useRef,useState} from 'react';
import {useAuth} from '../../context/AuthContext';
import {api,notice} from '../../lib/api';
import {QuickDeck,Field} from '../../components/DataUI';
import {AdminHeader,AdminFilters,AdminTable,AdminStats,AdminState,AdminDrawer,AdminError,useAdminFeed,roles,dateText} from './AdminUI';

function AccountEditor({initial,customer,onClose,onSaved}){
 const [form,setForm]=useState({...initial,password:''}),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),saving=useRef(false),{reload}=useAuth();
 const set=(key,value)=>{setForm(old=>({...old,[key]:value}));setErrors(old=>({...old,[key]:'',form:''}));};
 const root=String(initial.username||'').toLowerCase()==='admin';
 const save=async event=>{event.preventDefault();if(saving.current)return;const issues={};for(const key of ['fullName','email','status',...(!customer?['username','role']:[])])if(!String(form[key]||'').trim())issues[key]='This field is required';if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim()))issues.email='Enter a valid email';if(!initial.id&&!form.password)issues.password='Password is required';else if(form.password&&[...form.password].length<8)issues.password='Use at least 8 characters';setErrors(issues);if(Object.keys(issues).length)return;saving.current=true;setBusy(true);try{await api('/api/v1/users/'+(initial.id?'update/'+initial.id:'add'),{method:'POST',body:JSON.stringify({...form,fullName:form.fullName.trim(),email:form.email.trim()})});await reload();onSaved();notice(initial.id?'Account updated':'User created');}catch(error){setErrors({...error.fields,form:error.message});}finally{saving.current=false;setBusy(false);}};
 const fields=customer?[['fullName','Full name'],['email','Email','email'],['phoneNumber','Phone number','text',true],['address','Address','text',true],['city','City','text',true]]:[['fullName','Full name'],['username','Username'],['password',initial.id?'New password':'Password','password',Boolean(initial.id)],['email','Email','email'],['phoneNumber','Phone number','text',true],['address','Address','text',true],['city','City','text',true]];
 return <AdminDrawer title={initial.id?(customer?'Edit customer':'Edit user'):'New user'} onClose={onClose} busy={busy}><form noValidate onSubmit={save}><fieldset disabled={busy} className="admin-editor-fields">{fields.map(([key,label,type='text',optional=false])=><Field key={key} label={label} optional={optional} error={errors[key]}><Input validationKey={key} className="input-dark" type={type} aria-invalid={!!errors[key]} readOnly={key==='username'&&Boolean(initial.id)} placeholder={key==='fullName'?'e.g. Kasun Dias':key==='username'?'e.g. kasun.dias':undefined} value={form[key]||''} onChange={event=>set(key,event.target.value)}/>{key==='password'&&initial.id&&<small>Leave empty to keep the current password.</small>}</Field>)}{!customer&&<Field label="Assigned role" error={errors.role}><div className="admin-select"><Select validationKey="role" className="input-dark" disabled={root} value={form.role||'Customer'} onChange={event=>set('role',event.target.value)}>{roles.map(role=><option key={role}>{role}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div></Field>}<Field label="Account status" error={errors.status}><div className="admin-select"><Select validationKey="status" className="input-dark" disabled={root} value={form.status||'Active'} onChange={event=>set('status',event.target.value)}>{['Active','Deactivated'].map(value=><option key={value}>{value}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div></Field>{root&&<p className="admin-meta">The root administrator's role and active status are protected.</p>}</fieldset>{errors.form&&<p className="admin-error" role="alert">{errors.form}</p>}<footer><button disabled={busy} type="button" className="admin-action" onClick={onClose}>Cancel</button><button disabled={busy} type="submit" className="btn-accent">{busy?'Saving...':initial.id?'Save changes':'Create user'}</button></footer></form></AdminDrawer>;
}
export default function AdminAccounts({customer=false}){
 const workspace=useAdminFeed('/api/v1/'+(customer?'customers':'users')),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[role,setRole]=useState(''),[selected,setSelected]=useState(null),[working,setWorking]=useState(null),pending=useRef(false);
 const all=workspace.data[customer?'customers':'users']||[],rows=all.filter(row=>(!status||row.status===status)&&(!role||row.role===role)&&[row.fullName,row.username,row.email,row.phoneNumber,row.address,row.city].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase())));
 const toggle=async row=>{if(pending.current||row.username?.toLowerCase()==='admin')return;pending.current=true;setWorking(row.id);try{await api('/api/v1/users/status/'+row.id,{method:'POST'});await workspace.load();notice('Account status updated');}catch(error){workspace.setError(error.message);}finally{pending.current=false;setWorking(null);}};
 const filters=[...(!customer?[{label:'Filter role',all:'All roles',options:roles,value:role,change:setRole}]:[]),{label:'Filter status',all:'All status',options:[...new Set(['Active','Deactivated',...all.map(item=>item.status).filter(Boolean)])],value:status,change:setStatus}];
 const controls=<AdminFilters label="Search name, username, email" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} filters={filters} onReset={()=>{setDraft('');setQuery('');setStatus('');setRole('');}}>{!customer&&<button className="btn-accent" onClick={()=>setSelected({role:'Customer',status:'Active'})}>Quick create <i aria-hidden="true" className="fa-solid fa-plus"/></button>}</AdminFilters>;
 const stats=customer?[['Total customers',workspace.data.totalCustomers??all.length],['Active',workspace.data.activeCount],['Deactivated',all.filter(item=>item.status==='Deactivated').length]]:[['Total users',workspace.data.totalCount??all.length],['Active',workspace.data.activeCount],['Admins',workspace.data.adminCount],['Staff',workspace.data.staffCount],['Customers',workspace.data.customerCount]];
 return <div className="admin-accounts"><AdminHeader title={customer?'Customer directory.':'User administration.'}/><AdminStats items={stats}/><AdminError workspace={workspace}/>{controls}<QuickDeck>{controls}</QuickDeck><AdminTable rows={rows} loading={workspace.loading} name={customer?'Customers':'Users'} columns={[{label:customer?'Customer':'User',width:'20%',render:row=><><strong>{row.fullName||'Unavailable'}</strong><span className="admin-meta">@{row.username}</span></>},{label:'Contact',width:customer?'19%':'22%',render:row=><><span>{row.email||'Unavailable'}</span><span className="admin-meta">{row.phoneNumber||'No phone supplied'}</span></>},customer?{label:'Address',width:'17%',render:row=><span>{[row.address,row.city].filter(Boolean).join(', ')||'Not supplied'}</span>}:{label:'Role',width:'12%',render:row=><AdminState value={row.role}/>},{label:'Status',width:customer?'10%':'11%',render:row=><AdminState value={row.status}/>},{label:customer?'Joined':'Created at',width:customer?'11%':'12%',render:row=><span className="admin-meta">{dateText(row.createdAt)}</span>},{label:'Actions',width:'19%',render:row=><div className="admin-actions"><button className="admin-action" disabled={working!==null||row.username?.toLowerCase()==='admin'} onClick={()=>toggle(row)}>{row.status==='Active'?'Deactivate':'Reactivate'}</button><button className="admin-action" onClick={()=>setSelected({...row})}>Edit</button></div>}]}/>{selected&&<AccountEditor key={selected.id||'new'} customer={customer} initial={selected} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);workspace.load();}}/>}</div>;
}
