import {Input,Select} from '../../components/Validation';
import {useState,useEffect,useRef,useCallback} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {api} from '../../lib/api';
import {getStatusTone,getPaginationRange,exportTableToCsv} from '../../lib/tableUtils';

export const roles=['Admin','Manager','Cashier','Mechanic','Customer'];
export const dateText=(value,time=false)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Colombo',...(time?{}:{year:'numeric',month:'short',day:'2-digit'})}):'Unavailable';
export function AdminState({value}){const tone=getStatusTone(value);return <span className={`admin-state status-${tone}`}>{value||'Unknown'}</span>;}
export function AdminHeader({title,kicker='Governance & users',children}){return <div className="admin-page-heading"><div><p>{kicker}</p><h1>{title}</h1></div>{children}</div>;}
export function AdminStats({items}){return <section className="admin-stats" aria-label="Overview statistics">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{value??0}</strong></div>)}</section>;}
export function AdminFilters({draft,setDraft,query,onSearch,filters=[],onReset,label='Search records',children}){return <div className="admin-filters"><form noValidate className="admin-search" onSubmit={event=>{event.preventDefault();onSearch(draft.trim());}}><Input className="input-dark" aria-label={label} placeholder={label?label+'...':'Search records...'} value={draft} onChange={event=>setDraft(event.target.value)}/>{draft&&<button type="button" aria-label="Clear search" onClick={()=>{setDraft('');onSearch('');}}><i aria-hidden="true" className="fa-solid fa-xmark"/></button>}<button type="submit" aria-label="Search"><i aria-hidden="true" className="fa-solid fa-magnifying-glass"/></button></form>{filters.map(filter=><div className="admin-select" key={filter.label}><Select validationKey="value" className="input-dark" aria-label={filter.label} value={filter.value} onChange={event=>filter.change(event.target.value)}><option value="">{filter.all}</option>{filter.options.map(value=><option key={value}>{value}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div>)}{(draft||query||filters.some(item=>item.value))&&<button className="admin-action" onClick={onReset}>Reset filters</button>}{children}</div>;}
export function AdminTable({rows,columns,loading,name='Records'}){const signature=rows.map(row=>row.id).join('|'),[paging,setPaging]=useState({signature,size:10,page:1}),reduced=useReducedMotion();const {size}=paging,pages=Math.max(1,Math.ceil(rows.length/size)),page=Math.min(signature===paging.signature?paging.page:1,pages);const pageRange=getPaginationRange(page,pages);return <><div className="admin-table-wrap"><table className="admin-table"><colgroup><col style={{width:'4%'}}/>{columns.map(column=><col key={column.label} style={{width:column.width}}/>)}</colgroup><thead><tr><th>#</th>{columns.map(column=><th>{column.label}</th>)}</tr></thead><tbody>{!loading&&rows.slice((page-1)*size,page*size).map((row,index)=><motion.tr initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{duration:.2,delay:index*.025}} key={row.id}><td className="admin-meta">{(page-1)*size+index+1}</td>{columns.map(column=><td key={column.label}>{column.render?column.render(row):row[column.key]??'Unavailable'}</td>)}</motion.tr>)}{(loading||!rows.length)&&<tr><td colSpan={columns.length+1} className="admin-empty">{loading?'Loading records...':'NO RECORDS FOUND'}</td></tr>}</tbody></table></div><nav className="admin-pagination portal-pagination" aria-label={name+' pagination'}><div className="portal-pagination-info"><span>Showing {rows.length?(page-1)*size+1:0} &ndash; {Math.min(page*size,rows.length)} of {rows.length}</span><label className="manager-service-row-select-wrap"><span>Rows:</span><select className="manager-row-select" aria-label="Rows per page" value={size} onChange={e=>setPaging({signature,size:Number(e.target.value),page:1})}>{[10,15,20,50].map(val=><option key={val} value={val}>{val}</option>)}</select></label></div><div className="portal-pagination-buttons"><button aria-label="Previous page" disabled={page===1} onClick={()=>setPaging({signature,size,page:page-1})}>Prev</button>{pageRange.map((p,idx)=>p==='...'?<span key={`dots-${idx}`} className="manager-page-ellipsis">&hellip;</span>:<button key={p} aria-label={`Page ${p}`} aria-current={page===p?'page':undefined} className={`manager-page-num ${page===p?'is-active':''}`} onClick={()=>setPaging({signature,size,page:p})}>{p}</button>)}<button aria-label="Next page" disabled={page===pages} onClick={()=>setPaging({signature,size,page:page+1})}>Next</button></div></nav></>;}
export function AdminDrawer({title,onClose,busy,children}){const ref=useRef(null),close=useRef(onClose),working=useRef(busy),reduced=useReducedMotion();useEffect(()=>{close.current=onClose;working.current=busy;},[onClose,busy]);useEffect(()=>{const old=document.body.style.overflow,previous=document.activeElement;document.body.style.overflow='hidden';const elements=()=>[...ref.current.querySelectorAll('input:not(:disabled),button:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')].filter(item=>item.getClientRects().length);const frame=requestAnimationFrame(()=>elements()[0]?.focus());const handle=event=>{if(event.key==='Escape'&&!working.current)close.current();if(event.key==='Tab'){const list=elements();if(event.shiftKey&&document.activeElement===list[0]){event.preventDefault();list.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===list.at(-1)){event.preventDefault();list[0]?.focus();}}};window.addEventListener('keydown',handle);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',handle);document.body.style.overflow=old;if(previous?.isConnected)previous.focus({preventScroll:true});};},[]);return <motion.div className="admin-drawer-backdrop" initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{duration:.2}}><motion.section className="admin-drawer" role="dialog" aria-modal="true" aria-label={title} ref={ref} initial={reduced?false:{x:60,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:.2}}><header><div><p>Account administration</p><h2>{title}</h2></div><button disabled={busy} aria-label="Close dialog" onClick={onClose}><i aria-hidden="true" className="fa-solid fa-xmark"/></button></header>{children}</motion.section></motion.div>;}
export function useAdminFeed(endpoint){const [data,setData]=useState({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),request=useRef(0);const load=useCallback(async()=>{const current=++request.current;try{const feed=await api(endpoint);if(current===request.current){setData(feed);setError('');}}catch(error){if(current===request.current)setError(error.message);}finally{if(current===request.current)setLoading(false);}},[endpoint]);useEffect(()=>{load();window.addEventListener('fuelcore:refresh',load);return()=>{request.current++;window.removeEventListener('fuelcore:refresh',load);};},[load]);return {data,error,setError,loading,load};}
export function AdminError({workspace}){return workspace.error&&<p className="admin-error" role="alert">{workspace.error} <button className="admin-action" onClick={workspace.load}>Retry</button></p>;}
