import {Input,Select} from '../../components/Validation';
import {useEffect,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {motion} from 'framer-motion';
import {api} from '../../lib/api';
import {Badge,QuickDeck} from '../../components/DataUI';
import {ServiceHeader,ServiceTable} from './ManagerServiceUI';

export default function ManagerServiceHistory(){const [params,setParams]=useSearchParams();const plate=(params.get('licensePlate')||'').trim().toUpperCase();return <HistoryLookup key={plate} plate={plate} setParams={setParams}/>;}
function HistoryLookup({plate,setParams}){
  const [draft,setDraft]=useState(plate),[feed,setFeed]=useState({bookings:[],vehicles:[]}),[jobs,setJobs]=useState([]),[loading,setLoading]=useState(Boolean(plate)),[error,setError]=useState(''),[notesError,setNotesError]=useState(''),[status,setStatus]=useState(''),[version,setVersion]=useState(0);
  const navigate=useNavigate();
  useEffect(()=>{
    if(!plate)return;let alive=true;
    const load=async()=>{setLoading(true);const [bookings,workshop]=await Promise.allSettled([api('/api/workshop/bookings'),api('/api/workshop')]);if(!alive)return;if(bookings.status==='fulfilled'){setFeed(bookings.value);setError('');}else setError(bookings.reason.message);if(workshop.status==='fulfilled'){setJobs(workshop.value.jobCards||[]);setNotesError('');}else setNotesError('Technician notes could not be loaded. '+workshop.reason.message);setLoading(false);};
    load();window.addEventListener('fuelcore:refresh',load);return()=>{alive=false;window.removeEventListener('fuelcore:refresh',load);};
  },[plate,version]);
  const clear=()=>{setDraft('');setError('');setStatus('');setParams({});};
  const search=event=>{event.preventDefault();const value=draft.trim().toUpperCase();if(!value){setError('Please enter a registration plate.');return;}setError('');if(value===plate)setVersion(v=>v+1);else setParams({licensePlate:value});};
  const book=()=>{const vehicle=feed.vehicles.find(vehicle=>vehicle.licensePlate?.trim().toUpperCase()===plate)||{licensePlate:plate};navigate('/dashboard/bookings',{state:{openNewBooking:true,...(plate?{vehicle}:{})}});};
  const history=feed.bookings.filter(booking=>booking.licensePlate?.trim().toUpperCase()===plate);
  const controls=<div className="manager-history-controls"><form noValidate onSubmit={search} className="manager-history-search"><div><Input required validationKey="licensePlate" className="input-dark" aria-label="Registration plate" placeholder="Enter Registration Plate (e.g. CAA-1234)" value={draft} onChange={event=>setDraft(event.target.value.toUpperCase())}/>{draft&&<button type="button" className="manager-history-clear-input" aria-label="Clear plate text" onClick={()=>setDraft('')}><i aria-hidden="true" className="fa-solid fa-xmark"/></button>}</div><button className="btn-accent manager-service-primary" type="submit">Search records</button></form>{plate&&history.length>0&&<div className="manager-service-select"><Select className="input-dark" aria-label="Filter status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All Status</option>{[...new Set(history.map(row=>row.status))].map(value=><option key={value}>{value}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div>}</div>;
  return <motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.2}} className="manager-service manager-history"><ServiceHeader kicker="Archive lookup" title="Service history."><div className="manager-service-actions"><button className="manager-service-action" onClick={clear}>Clear archive</button><button className="btn-accent manager-service-primary" onClick={book}>New booking</button></div></ServiceHeader><div className="manager-history-search-card">{controls}</div><QuickDeck><div className="manager-history-quick">{controls}<button className="manager-service-action" onClick={clear}>Clear archive</button><button className="btn-accent manager-service-primary" onClick={book}>New booking</button></div></QuickDeck>{error&&<p role="alert" className="text-brand-accent my-5">{error}{plate&&<button onClick={()=>setVersion(v=>v+1)} className="ml-3">Retry</button>}</p>}{notesError&&<p role="alert" className="text-gray-400 my-5">{notesError} <button onClick={()=>setVersion(v=>v+1)}>Retry notes</button></p>}{!plate?<div className="manager-history-empty"><h2>Archive access.</h2><p>Enter a customer's registration plate to retrieve their service appointments, maintenance history and technician notes.</p><button className="manager-service-action" onClick={()=>navigate('/dashboard/vehicles')}>View fleet registry</button></div>:loading?<p className="manager-history-loading">Retrieving archives...</p>:history.length?<><div className="manager-history-results"><h2>Archive results</h2><span>{plate}</span></div><ServiceTable name="Service history" rows={history.filter(row=>!status||row.status===status)} empty="NO RECORDS MATCH THIS STATUS" columns={[
    {label:'Date',width:'17%',render:row=><><span className="font-mono">{row.serviceDate}</span><span className="manager-service-meta">{row.timeSlot}</span><span className="manager-service-meta font-mono">{row.referenceNumber}</span></>},
    {key:'serviceType',label:'Package',width:'20%'},{key:'customerName',label:'Customer',width:'20%'},
    {label:'Technician notes',width:'25%',render:row=><div className="manager-history-notes"><p>{notesError?'Technician notes unavailable':jobs.find(job=>job.referenceNumber===row.referenceNumber)?.mechanicNotes||'No technician notes'}</p>{row.notes&&<span className="manager-service-meta">Booking: {row.notes}</span>}</div>},
    {label:'Status',width:'13%',render:row=><Badge value={row.status}/>}
  ]}/></>:!error&&<div className="manager-history-empty"><h2>No service records.</h2><p>No appointments were found for <strong className="font-mono">{plate}</strong>.</p><button className="btn-accent manager-service-primary" onClick={book}>Schedule first appointment</button></div>}</motion.div>;
}
