import {Input,Select,TextArea} from '../../components/Validation';
import {useState} from 'react';
import {QuickDeck,Field,money} from '../../components/DataUI';
import {PhotoEditor,photoError,photoPayload} from '../../components/ItemPhoto';
import {ServiceHeader,ServiceFilters} from './ManagerServiceUI';
import {InventoryBadge,InventoryModal} from './inventory/InventoryUI';
import {CatalogCards,CatalogMedia} from './catalog/ManagerCatalogUI';
import useCatalogWorkspace from './catalog/useCatalogWorkspace';

const icons=[['fa-wrench','Wrench'],['fa-oil-can','Oil'],['fa-car','Car'],['fa-car-battery','Battery'],['fa-gears','Gears'],['fa-droplet','Fluids'],['fa-temperature-half','Temperature'],['fa-screwdriver-wrench','Repairs'],['fa-gauge-high','Diagnostics'],['fa-spray-can-sparkles','Detailing']];
function ServiceEditor({workspace}){
  const initial=workspace.selected,[form,setForm]=useState({...initial}),[photo,setPhoto]=useState(null),[removed,setRemoved]=useState(false),[photoIssue,setPhotoIssue]=useState(''),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false);
  const set=(key,value)=>{setForm(old=>({...old,[key]:value}));setErrors(old=>({...old,[key]:'',form:''}));};
  const save=async event=>{
    event.preventDefault();if(busy)return;const issues={},payload={...form};
    for(const key of ['name','category','estimatedDuration']){payload[key]=String(form[key]||'').trim();if(!payload[key])issues[key]='This field is required';}
    if(form.estimatedCost==null||form.estimatedCost===''||!Number.isFinite(Number(form.estimatedCost))||Number(form.estimatedCost)<0)issues.estimatedCost='Enter a nonnegative estimated cost';
    payload.estimatedCost=Number(form.estimatedCost);payload.popular=Boolean(form.popular);
    const matches=[...String(form.estimatedDuration||'').matchAll(/(\d+(?:\.\d+)?)\s*(hours?|hrs?|h|minutes?|mins?|m)/gi)],minutes=matches.reduce((sum,match)=>sum+Number(match[1])*(match[2].toLowerCase().startsWith('h')?60:1),0);
    if(payload.estimatedDuration&&(minutes<=0||minutes>540))issues.estimatedDuration='Use a duration from 1 minute to 9 hours, e.g. 45 Minutes or 1.5 Hours';
    setErrors(issues);if(Object.keys(issues).length||photoIssue)return;setBusy(true);
    try{await workspace.save(photoPayload('service',payload,photo,removed));}catch(error){setErrors({form:error.message});}finally{setBusy(false);}
  };
  return <InventoryModal title={initial.id?'Edit service':'Create new service'} kicker="Service catalog" variant="parts" busy={busy} onClose={()=>workspace.setSelected(null)}><form className="manager-catalog-form" noValidate onSubmit={save}><fieldset disabled={busy}><div className="manager-inventory-fields">{[['name','Service name','text','e.g. Engine Oil Change'],['category','Category','text','e.g. Diagnostics & Mechanical'],['estimatedCost','Estimated cost (Rs.)','number','4000.00'],['estimatedDuration','Estimated duration','text','e.g. 1 Hour']].map(([key,label,type,placeholder])=><Field key={key} label={label} error={errors[key]}><Input validationKey={key} className="input-dark" type={type} min={type==='number'?0:undefined} step={type==='number'?'.01':undefined} value={form[key]??''} placeholder={placeholder} onChange={event=>set(key,event.target.value)}/></Field>)}<div className="manager-catalog-wide"><Field label="Short description" optional><TextArea validationKey="shortDescription" className="input-dark" placeholder="Brief description of what this service includes..." value={form.shortDescription||''} onChange={event=>set('shortDescription',event.target.value)}/></Field></div><div className="manager-catalog-wide"><p className="manager-icon-heading">Service icon</p><div className="manager-icon-options" role="group" aria-label="Service icon">{icons.map(([value,label])=><button type="button" key={value} aria-label={label+' icon'} aria-pressed={form.icon===value} className={form.icon===value?'is-active':''} onClick={()=>set('icon',value)}><i aria-hidden="true" className={'fa-solid '+value}/></button>)}{form.icon&&!icons.some(([value])=>value===form.icon)&&<button type="button" aria-label="Existing service icon" aria-pressed="true" className="is-active"><i aria-hidden="true" className={'fa-solid '+form.icon}/></button>}</div></div><label className="manager-popular-choice manager-catalog-wide"><Input type="checkbox" checked={Boolean(form.popular)} onChange={event=>set('popular',event.target.checked)}/><span>Mark as Popular Service<small>Popular services are highlighted to customers</small></span></label></div><PhotoEditor kind="service" saved={initial.imageUrl} file={photo} removed={removed} error={photoIssue} onChange={file=>{const issue=photoError(file);setPhotoIssue(issue||'');if(!issue){setPhoto(file);setRemoved(false);}}} onRemove={()=>{setPhoto(null);setRemoved(true);setPhotoIssue('');}}/></fieldset>{errors.form&&<p role="alert" className="manager-inventory-error">{errors.form}</p>}<footer><button type="button" disabled={busy} className="manager-service-action" onClick={()=>workspace.setSelected(null)}>Cancel</button><button type="submit" disabled={busy} className="btn-accent manager-inventory-submit">{busy?'Saving…':initial.id?'Save changes':'Create service'}</button></footer></form></InventoryModal>;
}
export default function ManagerServiceCatalog(){
  const workspace=useCatalogWorkspace('/api/services'),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState('');
  const categories=[...new Set(workspace.data.services.map(item=>item.category).filter(Boolean))];
  const rows=workspace.data.services.filter(item=>(!status||(item.active?'Active':'Inactive')===status)&&(!category||item.category===category)&&`${item.name} ${item.category} ${item.shortDescription||''}`.toLowerCase().includes(query.toLowerCase()));
  const controls=<ServiceFilters label="Search services" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} status={status} onStatus={setStatus} statuses={['Active','Inactive']}><div className="manager-service-select"><Select className="input-dark" aria-label="Filter category" value={category} onChange={event=>setCategory(event.target.value)}><option value="">All categories</option>{categories.map(value=><option key={value}>{value}</option>)}</Select><i aria-hidden="true" className="fa-solid fa-chevron-down"/></div>{category&&<button className="manager-service-action" onClick={()=>setCategory('')}>Clear category</button>}<button className="btn-accent manager-service-primary" onClick={()=>workspace.setSelected({icon:'fa-wrench',popular:false,estimatedDuration:'1 Hour'})}>Create service</button></ServiceFilters>;
  return <div className="manager-catalog manager-inventory"><ServiceHeader kicker="Offers & promotions" title="Service catalog.">{controls}</ServiceHeader><QuickDeck>{controls}</QuickDeck>{workspace.error&&<p role="alert" className="manager-inventory-error">{workspace.error}<button onClick={workspace.load}>Retry</button></p>}<CatalogCards rows={rows} name="Service catalog" loading={workspace.loading}>{item=><><CatalogMedia name={item.name} src={item.imageUrl} kind="service" popular={item.popular}/><div className="manager-item-copy"><p className="manager-item-category"><span>{item.category}</span><span className="manager-catalog-icon"><i aria-hidden="true" className={'fa-solid '+(item.icon||'fa-wrench')}/></span></p><h2>{item.name}</h2><p className="manager-item-description">{item.shortDescription||'No description recorded.'}</p><div className="manager-item-meta"><strong>Rs. {money(item.estimatedCost)}</strong><span>{item.estimatedDuration}</span><InventoryBadge value={item.active?'Active':'Inactive'}/></div><div className="manager-item-footer"><button className="manager-service-action" onClick={()=>workspace.setSelected({...item})}>Edit</button><button className="manager-service-action" disabled={workspace.action!==null} onClick={()=>workspace.act(item,'toggle')}>{item.active?'Deactivate':'Activate'}</button><button className="manager-service-action" disabled={workspace.action!==null} onClick={()=>workspace.act(item,'delete')}>Delete</button></div></div></>}</CatalogCards>{workspace.selected&&<ServiceEditor workspace={workspace}/>}</div>;
}
