import {useState} from 'react';
import {QuickDeck} from '../../components/DataUI';
import {ServiceHeader,ServiceFilters,ServiceTable} from './ManagerServiceUI';
import useInventoryWorkspace from './inventory/useInventoryWorkspace';
import {InventoryBadge,InventoryMessages,InventoryModal} from './inventory/InventoryUI';
import InventoryForm from './inventory/InventoryForm';
import {parseGoods} from './inventory/inventoryValues';

export default function ManagerSuppliers(){
  const workspace=useInventoryWorkspace('suppliers'),[draft,setDraft]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[details,setDetails]=useState(null);
  const controls=<ServiceFilters label="Search suppliers" draft={draft} setDraft={setDraft} query={query} onSearch={setQuery} status={status} onStatus={setStatus} statuses={['Active','Inactive']}><button className="btn-accent manager-service-primary" onClick={()=>workspace.setSelected({status:'Active'})}>Add supplier</button></ServiceFilters>;
  const rows=workspace.rows.filter(supplier=>(!status||supplier.status===status)&&[supplier.supplierName,supplier.company,supplier.contactNumber,supplier.email,supplier.deliverySchedule,supplier.fuelTypesSupplied,'SUP-'+supplier.id].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase())));
  return <div className="manager-inventory manager-inventory-suppliers"><ServiceHeader kicker="Inventory infrastructure" title="Suppliers.">{controls}</ServiceHeader><InventoryMessages workspace={workspace}/><QuickDeck>{controls}</QuickDeck><ServiceTable name="Suppliers" rows={rows} loading={workspace.loading} columns={[
    {label:'ID',width:'8%',render:supplier=><span className="manager-service-id">SUP-{supplier.id}</span>},{key:'supplierName',label:'Supplier name',width:'21%',render:supplier=><strong>{supplier.supplierName}</strong>},{key:'company',label:'Company',width:'22%',render:supplier=><>{supplier.company}{supplier.deliverySchedule&&<small className="manager-service-meta">Delivery: {supplier.deliverySchedule}</small>}</>},{key:'contactNumber',label:'Contact',width:'15%',render:supplier=><>{supplier.contactNumber}{supplier.email&&<small className="manager-service-meta">{supplier.email}</small>}</>},{label:'Status',width:'9%',render:supplier=><InventoryBadge value={supplier.status}/>},{label:'Actions',width:'20%',render:supplier=><div className="manager-service-actions"><button className="manager-service-action" onClick={()=>setDetails(supplier)}>Supplied goods</button><button className="manager-service-action" onClick={()=>workspace.setSelected({...supplier})}>Edit</button><button className="manager-service-action" disabled={workspace.deleting!==null} onClick={()=>workspace.erase(supplier)}>{workspace.deleting===supplier.id?'Deleting…':'Delete'}</button></div>}
  ]}/>{workspace.selected&&<InventoryForm kind="suppliers" initial={workspace.selected} workspace={workspace}/>} {details&&<InventoryModal title={details.supplierName} kicker="Supplier details" variant="goods" onClose={()=>setDetails(null)}><p className="manager-inventory-details-intro">Supplied goods & materials</p>{parseGoods(details.fuelTypesSupplied).length?<ul className="manager-inventory-goods-details">{parseGoods(details.fuelTypesSupplied).map(item=><li key={item}><i aria-hidden="true" className="fa-solid fa-box"/>{item}</li>)}</ul>:<p className="manager-inventory-empty">No supplied goods recorded.</p>}<footer><button className="manager-service-action" onClick={()=>setDetails(null)}>Close</button></footer></InventoryModal>}</div>;
}
